"""create table LeadBinding

Revision ID: 1f757384cf5c
Revises: 4fbf1268f062
Create Date: 2025-07-01 22:27:59.995762

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f757384cf5c'
down_revision: Union[str, Sequence[str], None] = '4fbf1268f062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leadbinding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_number', sa.BigInteger(), nullable=False),
    sa.Column('operator_number', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leadbinding_lead_id'), 'leadbinding', ['lead_id'], unique=False)
    op.create_index(op.f('ix_leadbinding_operator_number'), 'leadbinding', ['operator_number'], unique=False)
    op.create_index(op.f('ix_leadbinding_user_number'), 'leadbinding', ['user_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leadbinding_user_number'), table_name='leadbinding')
    op.drop_index(op.f('ix_leadbinding_operator_number'), table_name='leadbinding')
    op.drop_index(op.f('ix_leadbinding_lead_id'), table_name='leadbinding')
    op.drop_table('leadbinding')
    # ### end Alembic commands ###
