"""...

Revision ID: 416060a60eea
Revises:
Create Date: 2025-07-28 00:08:32.513557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "416060a60eea"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("client_phone", sa.String(), nullable=False),
        sa.Column("operator_phone", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deals_conversation_id"), "deals", ["conversation_id"], unique=False
    )
    op.create_table(
        "operatorsdata",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("number_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operatorsdata_account_id"),
        "operatorsdata",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operatorsdata_number_id"), "operatorsdata", ["number_id"], unique=False
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sender", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("media", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("sent", "delivered", "read", name="statusenum"),
            nullable=False,
        ),
        sa.Column("template_id", sa.BigInteger(), nullable=True),
        sa.Column("deals_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deals_id"],
            ["deals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_sender"), "messages", ["sender"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_sender"), table_name="messages")
    op.drop_table("messages")
    op.drop_table("templates")
    op.drop_index(op.f("ix_operatorsdata_number_id"), table_name="operatorsdata")
    op.drop_index(op.f("ix_operatorsdata_account_id"), table_name="operatorsdata")
    op.drop_table("operatorsdata")
    op.drop_index(op.f("ix_deals_conversation_id"), table_name="deals")
    op.drop_table("deals")
    # ### end Alembic commands ###
