"""add indexes to user_number and operator_number

Revision ID: 4fbf1268f062
Revises: 
Create Date: 2025-06-29 14:53:25.554258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbf1268f062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_number', sa.BigInteger(), nullable=False),
    sa.Column('operator_number', sa.BigInteger(), nullable=False),
    sa.Column('from_number', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_operator_number'), 'messages', ['operator_number'], unique=False)
    op.create_index(op.f('ix_messages_user_number'), 'messages', ['user_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_number'), table_name='messages')
    op.drop_index(op.f('ix_messages_operator_number'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
